// 用户模块
export const USER_LOGIN = 'USER_LOGIN'
export const GET_CURRENT_DATA = 'GET_CURRENT_DATA'
export const GET_USER_INFO = 'GET_USER_INFO'
export const SEND_SMS_CODE = 'SEND_SMS_CODE'

// 申请模块
export const GET_LOAN_LIST = 'GET_LOAN_LIST'
export const GET_LOAN_INFO = 'GET_LOAN_INFO'
export const GET_LOAN_LAST_DATA = 'GET_LOAN_LAST_DATA'
export const CHANGE_APP_COMPLETE_INFO = 'CHANGE_APP_COMPLETE_INFO'
